# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  run:
    desc: Run the code
    cmds:
      - go run ./cmd/main.go
  build:
    desc: Build the code
    cmds:
      - go build -o ./.build/main ./cmd/main.go 

  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
